#!/bin/bash
# Regenerate the Cloudflare real-IP list for nginx.
#
# Behind Cloudflare, $remote_addr is a Cloudflare edge IP. Without this,
# access logs, X-Real-IP and any IP-based limiting all see Cloudflare
# instead of the visitor. Re-run occasionally; Cloudflare does add ranges.
#
#   sudo bash deploy/cloudflare-realip.sh && sudo nginx -t && sudo nginx -s reload

set -euo pipefail

OUT="${1:-/etc/nginx/conf.d/00-cloudflare-realip.conf}"
TMP="$(mktemp)"

{
  echo "# Generated by deploy/cloudflare-realip.sh -- do not edit by hand."
  for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    # Cloudflare does not terminate the list with a newline; awk adds one.
    curl -fsSL "$url" | awk 'NF { print "set_real_ip_from " $0 ";" }'
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

# Refuse to install a truncated list if Cloudflare or the network hiccuped.
if [ "$(grep -c set_real_ip_from "$TMP")" -lt 10 ]; then
  echo "refusing to install: only $(grep -c set_real_ip_from "$TMP") ranges fetched" >&2
  rm -f "$TMP"
  exit 1
fi

install -m 0644 "$TMP" "$OUT"
rm -f "$TMP"
echo "wrote $OUT ($(grep -c set_real_ip_from "$OUT") ranges)"
